[data]
data=/A.I_DATA/jbnu/Samyung/1ST_ITGCN/ST-DTGCN/data/COVID_KOR_Confirmed/processed_confirmed
sensors_distance=/A.I_DATA/jbnu/Samyung/1ST_ITGCN/ST-DTGCN/data/COVID_KOR_Confirmed/kor_covid_W_matrix.csv
seed=42
batch_size=32
valid_batch_size=16
fill_zeros=False

[model]
num_of_vertices=17
in_dim=1
hidden_dims=[[16, 16],[16, 16]]
first_layer_embedding_size=16
out_layer_dim=256
d_model=16
n_heads=2
dropout=0.1
forward_expansion=4
history=12
horizon=12
strides=3
temporal_emb=True
spatial_emb=True
use_transformer=True
factor=20
attention_dropout=0.1128368367236193
output_attention=False
use_mask=True
activation=relu
use_adaptive_graph=True
norm_type=DyTanhNorm
ffn_activation=tanh
return_stability_stats=False
use_temporal_inception=True
use_informer=False

[train]
seed=42
learning_rate=0.0001
weight_decay=0.000008
lr_decay=True
lr_decay_rate=0.995
epochs=100
print_every=50
loss_function=mae
huber_delta = 1
patience=50
expid=2
max_grad_norm=4.968120026883448

save=/A.I_DATA/jbnu/Samyung/1ST_ITGCN/ST-DTGCN/checkpoints/KOR_States_Confirmed/
save_loss=/A.I_DATA/jbnu/Samyung/1ST_ITGCN/ST-DTGCN/losses/COVID_KOR/_Confirmed/
log_file=/A.I_DATA/jbnu/Samyung/1ST_ITGCN/ST-DTGCN/logs/COVID_KOR/log_COVID_KOR_Confirmed

[test]
log_file=/A.I_DATA/jbnu/Samyung/1ST_ITGCN/ST-DTGCN/logs/COVID_KOR/log_test_COVID_KOR_Confirmed
test_batch_size=16