[data]
data=/A.I_DATA/jbnu/Samyung/1ST_ITGCN/0326revision/data/COVID_ITA/processed_confirmed
sensors_distance=/A.I_DATA/jbnu/Samyung/1ST_ITGCN/0326revision/data/COVID_ITA/ita_covid_W_matrix.csv
seed=42
batch_size=32
valid_batch_size=16
fill_zeros=False

[model]
num_of_vertices=21
in_dim=1
hidden_dims=[[16, 16], [16, 16]]
first_layer_embedding_size=16
out_layer_dim=256
d_model=16
n_heads=2
dropout=0.1430446230402611
forward_expansion=4
history=12
horizon=12
strides=3
temporal_emb=True
spatial_emb=True
use_transformer=True
factor=20
attention_dropout=0.1128368367236193
output_attention=False
use_mask=True
activation=relu
use_adaptive_graph=True

norm_type=DyTanhNorm
# norm_type=LayerNorm
# norm_type=RMSNorm

ffn_activation=gelu
# ffn_activation=relu
# ffn_activation=gelu
# ffn_activation=tanh
# ffn_activation=swiglu

return_stability_stats=False
# return_stability_stats=True



# For the Informer ONLY (Not needed for this project)
use_informer=True

[train]
seed=42
learning_rate=0.0003504639060065192
weight_decay=0.000007298088023482183
lr_decay=False
lr_decay_rate=0.995
epochs=100
print_every=50
loss_function=mae  
save=/A.I_DATA/jbnu/Samyung/1ST_ITGCN/0326revision/checkpoints/ITA_States_Confirmed/
save_loss=/A.I_DATA/jbnu/Samyung/1ST_ITGCN/0326revision/losses/COVID_ITA/_Confirmed/
expid=2
max_grad_norm=4.968120026883448
patience=50
log_file=/A.I_DATA/jbnu/Samyung/1ST_ITGCN/0326revision/logs/COVID_ITA/log_COVID_ITA_Confirmed

[test]
log_file=/A.I_DATA/jbnu/Samyung/1ST_ITGCN/0326revision/logs/COVID_ITA/log_test_COVID_ITA_Confirmed
test_batch_size=16